name: .NET

on: workflow_dispatch

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
        
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --no-restore
      
    - name: Publish win-x64
      run: dotnet publish -c Release -r win7-x64
      
    - name: Publish linux-x64
      run: dotnet publish -c Release -r linux-x64

    - name: Upload Server Build Artifact
      run: |
        cd /home/runner/work/PrettySus/PrettySus/PrettySus.Server/bin/Release/net5.0/linux-x64/publish/ && zip -r server-linux-x64.zip *

    - name: Upload Client Build Artifact
      run: |
        cd /home/runner/work/PrettySus/PrettySus/PrettySus.Client/bin/Release/net5.0/win7-x64/publish/ && zip -r client-win-x64.zip *
        
    - name: Get current date
      id: date
      run: echo "::set-output name=date::$(date +'%Y-%m-%dT%H:%M:%S')"
        
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}-${{ steps.date.outputs.date }}
        release_name: Release ${{ github.ref }}-${{ steps.date.outputs.date }}
        draft: false
        prerelease: false
        
    - name: Upload Server Asset
      id: upload-release-server-asset 
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: /home/runner/work/PrettySus/PrettySus/PrettySus.Server/bin/Release/net5.0/linux-x64/publish/server-linux-x64.zip
        asset_name: server-linux-x64.zip
        asset_content_type: application/zip
        
    - name: Upload Client Asset
      id: upload-release-client-asset 
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: /home/runner/work/PrettySus/PrettySus/PrettySus.Client/bin/Release/net5.0/win7-x64/publish/client-win-x64.zip
        asset_name: client-win-x64.zip
        asset_content_type: application/zip
